### ISSUE TITLE
no responses after the chain size reached the max value;

### ISSUE THREAD

**Issue by Pezhin** [brkn8102/Knutson_CSCI2270_FinalProject#3]
1. set initial table size to **10** and  maximum allowed chain length to **3** and enable the dynamic table resizing;
2. Try to add (abcd,10), (bcda,10), (cdab,10), (dcba,10). And when I input **(dcba,10)**, the executable just has no responses at all.
3. what is in terminal
   
   ```
    Enter the data element key (a string): dcba
    Enter the data element value (an integer): 10
    //no any responses and would not show the main menu
   ```
4. I am using g++.
   Am I the only one having this problem?

**Comment by brkn8102** [comment]
Yes, I agree that there is definitely a bug. I will update the README.md to document this as a known issue.
